### ISSUE TITLE
Is component-based installation planned?

### ISSUE THREAD

**Issue by parnosys** [grandchild/linux_installer#2]
Hello.

This is a very nice installer builder project we got there! I was searching an alternative to Qt Installer Framework and I saw this project. The only really bothering thing is that, as said in the description, partial installation is not allowed by this. Do you plan to integrate it or did you abandon this project?

**Comment by grandchild** [comment]
Hi,
thanks for your kind words and interest in the project!

It’s very much not abandoned, it just currently work the way it’s supposed to.

I don’t currently plan to implement component-based installation. It’s a possibly complex feature. However I am not against merging such a feature if someone wants to write it.

As a workaround, if your set of components and their possible combinations isn’t too large, you could create multiple installers, each of which represents a certain feature combination. That’s the way that we used this installer, and it greatly simplifies the creation and installation process, because we can basically create a set of folders beforehand (and with tools that do it better than this installer would, in our case a small python script) and pack installers from those.

I realize that this comes at the cost of users having to decide the features at download time instead of install time, but I encourage you to consider it!

**Comment by parnosys** [comment]
Ok, I can understand that position. I'll probably come back to stay tuned about the progress of your installer builder.
Nice work anyways, again!
